import React, { useEffect, useState } from 'react';

/**
 * SplashScreen — STATIC IMAGE version (v4).
 *
 * Reason: animated versions glitched in the wild (slow 4G hid the splash
 * for some users, Google Fonts failed, `background-clip: text` made letters
 * invisible). A static PNG renders identically on every device, every time.
 *
 * Image is generated by `/app/backend/scripts/generate_splash_image.py` and
 * lives at `/splash-celesta-glow.png` (served from React's `public/` folder,
 * so it's hashed + edge-cached by the build). 1080×1920, 136 KB.
 */
const SESSION_KEY = 'cg_splash_seen_v5';
const DEFAULT_IMG = process.env.PUBLIC_URL ? `${process.env.PUBLIC_URL}/splash-celesta-glow.png` : '/splash-celesta-glow.png';

export default function SplashScreen({ onDone }) {
  // Start with NO image so we don't flash the bundled default before the
  // admin-set splash arrives from /api/site-settings. Only when the fetch
  // completes do we render an <img> (admin's URL if set, bundled PNG as
  // fallback). This fixes the "old splash keeps showing" bug reported by
  // the merchant after they uploaded a new splash.
  const [imgSrc, setImgSrc] = useState(null);
  const [imgResolved, setImgResolved] = useState(false);
  const [visible, setVisible] = useState(() => {
    try { return !sessionStorage.getItem(SESSION_KEY); } catch (_) { return true; }
  });
  const [fadingOut, setFadingOut] = useState(false);

  // Fetch admin-set splash image (falls back silently to bundled PNG)
  useEffect(() => {
    if (!visible) return;
    let cancelled = false;
    fetch(`${process.env.REACT_APP_BACKEND_URL}/api/site-settings`)
      .then(r => r.json())
      .then(s => {
        if (cancelled) return;
        setImgSrc((s && s.splash_image) ? s.splash_image : DEFAULT_IMG);
        setImgResolved(true);
      })
      .catch(() => {
        if (cancelled) return;
        setImgSrc(DEFAULT_IMG);
        setImgResolved(true);
      });
    // Safety: if fetch hangs >1.2s, fall back to bundled default so users
    // never stare at a blank white screen.
    const t = setTimeout(() => {
      if (cancelled) return;
      setImgSrc((prev) => prev || DEFAULT_IMG);
      setImgResolved(true);
    }, 1200);
    return () => { cancelled = true; clearTimeout(t); };
  }, [visible]);

  const finish = React.useCallback(() => {
    if (!visible || fadingOut) return;
    setFadingOut(true);
    try { sessionStorage.setItem(SESSION_KEY, '1'); } catch (_) { /* noop */ }
    setTimeout(() => { setVisible(false); onDone?.(); }, 380);
  }, [visible, fadingOut, onDone]);

  // Pre-warm the homepage APIs while the splash is visible
  useEffect(() => {
    if (!visible) return;
    (async () => {
      try {
        const { cachedGet } = await import('../utils/apiCache');
        const API = process.env.REACT_APP_BACKEND_URL;
        await Promise.allSettled([
          cachedGet(`${API}/api/concerns`, { ttl: 60_000 }),
          cachedGet(`${API}/api/categories`, { ttl: 60_000 }),
          cachedGet(`${API}/api/subcategories`, { ttl: 60_000 }),
          cachedGet(`${API}/api/site-settings`, { ttl: 60_000 }),
          cachedGet(`${API}/api/combos`, { ttl: 60_000 }),
          cachedGet(`${API}/api/products?niche=anti-aging&page=1&limit=20`),
          cachedGet(`${API}/api/products?niche=skincare&page=1&limit=20`),
          cachedGet(`${API}/api/products?niche=cosmetics&page=1&limit=20`),
        ]);
      } catch (_) { /* best-effort */ }
    })();
  }, [visible]);

  useEffect(() => {
    if (!visible) { onDone?.(); return; }
    const t = setTimeout(finish, 2400);
    // 1.4 s grace before dismiss listeners arm — covers page-load scroll/touch noise
    let armed = false;
    const skip = () => { if (armed) finish(); };
    const arm = setTimeout(() => { armed = true; }, 1400);
    window.addEventListener('pointerdown', skip, { passive: true });
    window.addEventListener('keydown', skip);
    return () => {
      clearTimeout(t);
      clearTimeout(arm);
      window.removeEventListener('pointerdown', skip);
      window.removeEventListener('keydown', skip);
    };
  }, [visible, finish, onDone]);

  if (!visible) return null;

  return (
    <div
      data-testid="splash-screen"
      role="status"
      aria-label="Celesta Glow"
      style={{
        position: 'fixed',
        inset: 0,
        zIndex: 9999,
        backgroundColor: '#ffffff',
        colorScheme: 'light',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
        opacity: fadingOut ? 0 : 1,
        transition: 'opacity 380ms ease-in',
      }}
    >
      <img
        src={imgSrc || DEFAULT_IMG}
        onError={(e) => { if (e.currentTarget.src !== DEFAULT_IMG) e.currentTarget.src = DEFAULT_IMG; }}
        alt="Celesta Glow — The Most Trusted Skincare Ecommerce App of Kerala. Glow With Confidence."
        // Crisp on every density; never bigger than viewport, never smaller than 320 px wide.
        style={{
          maxWidth: '100%',
          maxHeight: '100%',
          width: 'auto',
          height: 'auto',
          objectFit: 'contain',
          opacity: imgResolved ? 1 : 0,
          transition: 'opacity 220ms ease-in',
        }}
        decoding="async"
        fetchPriority="high"
      />
    </div>
  );
}
