/**
 * AdminRoutines — viewer for routines generated on the customer-facing /routine page.
 * Shows skin profile, picked products + the optional selfie users uploaded.
 */
import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { useNavigate, Link } from 'react-router-dom';
import { ArrowLeft, ImageIcon, Sparkles, Sunrise, Moon, RefreshCw } from 'lucide-react';
import { getAdminToken } from '../../utils/adminAuth';

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;

export default function AdminRoutines() {
  const navigate = useNavigate();
  const [routines, setRoutines] = useState([]);
  const [loading, setLoading] = useState(true);
  const [expanded, setExpanded] = useState(null);
  const token = getAdminToken();

  const fetchData = async () => {
    setLoading(true);
    try {
      const r = await axios.get(`${API}/admin/routines`, { headers: { 'X-Admin-Token': token } });
      setRoutines(r.data.routines || []);
    } catch (e) {
      // ignore
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (!token) { navigate('/admin'); return; }
    fetchData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className="min-h-screen bg-gray-50 lg:ml-64" data-testid="admin-routines">
      <div className="max-w-5xl mx-auto px-4 py-8">
        <Link to="/admin/dashboard" className="inline-flex items-center gap-1 text-gray-500 hover:text-gray-900 text-sm mb-4">
          <ArrowLeft size={14} /> Back to dashboard
        </Link>
        <div className="flex items-center justify-between mb-5">
          <div>
            <h1 className="text-2xl font-bold text-gray-900">Routine reports</h1>
            <p className="text-sm text-gray-500">{routines.length} routine{routines.length === 1 ? '' : 's'} generated by customers</p>
          </div>
          <button onClick={fetchData} className="p-2 rounded-xl border border-gray-200 hover:bg-white" data-testid="routines-refresh">
            <RefreshCw size={16} className={loading ? 'animate-spin' : ''} />
          </button>
        </div>

        {loading ? (
          <div className="flex items-center justify-center py-20"><RefreshCw className="animate-spin text-green-500" /></div>
        ) : routines.length === 0 ? (
          <div className="bg-white rounded-2xl p-10 text-center border border-gray-100">
            <Sparkles className="w-10 h-10 mx-auto mb-3 text-gray-300" />
            <p className="text-sm text-gray-500">No routines generated yet.</p>
          </div>
        ) : (
          <div className="space-y-3">
            {routines.map(r => {
              const isOpen = expanded === r.id;
              return (
                <div key={r.id} className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden" data-testid={`routine-${r.id}`}>
                  <button onClick={() => setExpanded(isOpen ? null : r.id)} className="w-full p-4 flex items-center gap-3 text-left">
                    <div className="w-12 h-12 rounded-xl bg-emerald-50 flex items-center justify-center overflow-hidden flex-shrink-0">
                      {r.photo_url || r.photo_data
                        ? <img src={r.photo_url || r.photo_data} alt="" className="w-full h-full object-cover" />
                        : <ImageIcon className="w-5 h-5 text-emerald-400" />}
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="font-semibold text-gray-900 text-sm truncate">{r.skin_type} · {r.age}</p>
                      <p className="text-xs text-gray-500 truncate">Concerns: {r.concerns?.join(', ') || '—'}</p>
                    </div>
                    <span className="text-[11px] text-gray-400">{new Date(r.created_at).toLocaleString('en-IN', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' })}</span>
                  </button>

                  {isOpen && (
                    <div className="border-t border-gray-100 p-4 bg-gray-50">
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                        <div>
                          <h4 className="text-xs font-bold text-amber-700 flex items-center gap-1.5 mb-2"><Sunrise size={12} /> Morning ritual</h4>
                          <ul className="space-y-1 text-xs">
                            {r.am?.map((s, i) => (
                              <li key={`am-${i}`} className="flex items-center gap-2">
                                <span className="text-gray-500 w-20 truncate">{s.slot?.label}</span>
                                <span className="font-medium text-gray-900 truncate">{s.product_name || '—'}</span>
                              </li>
                            ))}
                          </ul>
                        </div>
                        <div>
                          <h4 className="text-xs font-bold text-violet-700 flex items-center gap-1.5 mb-2"><Moon size={12} /> Night ritual</h4>
                          <ul className="space-y-1 text-xs">
                            {r.pm?.map((s, i) => (
                              <li key={`pm-${i}`} className="flex items-center gap-2">
                                <span className="text-gray-500 w-20 truncate">{s.slot?.label}</span>
                                <span className="font-medium text-gray-900 truncate">{s.product_name || '—'}</span>
                              </li>
                            ))}
                          </ul>
                        </div>
                      </div>
                      {(r.photo_url || r.photo_data) && (
                        <div className="mt-4">
                          <p className="text-xs text-gray-500 mb-1">Uploaded selfie</p>
                          <img src={r.photo_url || r.photo_data} alt="" className="w-32 h-32 object-cover rounded-xl ring-1 ring-gray-200" />
                        </div>
                      )}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
